# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uKDyohZC61N0z-j0tcpUwu4x5dS0OZOU
"""

n=input("Enter a number")
if int(n)%2==0:
     print("Given number is an even number")
else:
     print("Given number is an odd number")